defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
    test-commit:
        <<: *defaults
        machine: true
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Install packages
                command: sudo apt-get update && sudo apt-get install -y --no-install-recommends debootstrap debian-archive-keyring qemu-user-static bmap-tools whois
            - run:
                name: Build rpi2 thinclient
                command: make rpi2-thinclient
            - run:
                name: Save build images
                command: |
                    mkdir -p ~/tmp
                    sudo mv ~/repo/images/*/*.img* ~/tmp
            - store_artifacts:
                path: ~/tmp
workflows:
    version: 2
    snapshot:
        jobs:
            - test-commit